import type { TeamMember } from '../types/TeamPage.types'

export const teamMembers: TeamMember[] = [
  {
    id: 1,
    name: '손지영',
    role: 'Project manager',
    avatar: '👨‍💼',
    rank: 1,
    contributionRate: 95,
    status: '우수',
    maxScore: 4.8,
    currentScore: 4.8,
  },
  {
    id: 2,
    name: '신택수',
    role: 'BE Engineer',
    avatar: '👨‍💻',
    rank: 2,
    contributionRate: 88,
    status: '우수',
    maxScore: 3.8,
    currentScore: 3.8,
  },
  {
    id: 3,
    name: '김재현',
    role: 'BE Engineer',
    avatar: '👨‍💼',
    rank: 3,
    contributionRate: 80,
    status: '보통',
    maxScore: 3.5,
    currentScore: 3.5,
  },
  {
    id: 4,
    name: '이지선',
    role: 'AI Engineer',
    avatar: '👩‍💻',
    rank: 4,
    contributionRate: 90,
    status: '보통',
    maxScore: 4.0,
    currentScore: 4.0,
  },
  {
    id: 5,
    name: '이혜수',
    role: 'AI Engineer',
    avatar: '👩‍💼',
    rank: 5,
    contributionRate: 82,
    status: '보통',
    maxScore: 3.6,
    currentScore: 3.6,
  },
  {
    id: 6,
    name: '조은정',
    role: 'FE Engineer',
    avatar: '👩‍💻',
    rank: 6,
    contributionRate: 77,
    status: '미흡',
    maxScore: 3.0,
    currentScore: 3.0,
  },
  {
    id: 7,
    name: '박지훈',
    role: 'FE Engineer',
    avatar: '👨‍💻',
    rank: 7,
    contributionRate: 75,
    status: '미흡',
    maxScore: 2.8,
    currentScore: 2.8,
  },
  {
    id: 8,
    name: '최민수',
    role: 'Designer',
    avatar: '👨‍🎨',
    rank: 8,
    contributionRate: 70,
    status: '미흡',
    maxScore: 2.5,
    currentScore: 2.5,
  },
  {
    id: 9,
    name: '이수진',
    role: 'Designer',
    avatar: '👩‍🎨',
    rank: 9,
    contributionRate: 68,
    status: '미흡',
    maxScore: 2.3,
    currentScore: 2.3,
  },
  {
    id: 10,
    name: '김영수',
    role: 'QA Engineer',
    avatar: '👨‍🔧',
    rank: 10,
    contributionRate: 65,
    status: '미흡',
    maxScore: 2.0,
    currentScore: 2.0,
  },
  {
    id: 11,
    name: '박지영',
    role: 'QA Engineer',
    avatar: '👩‍🔧',
    rank: 11,
    contributionRate: 60,
    status: '미흡',
    maxScore: 1.8,
    currentScore: 1.8,
  },
  {
    id: 12,
    name: '정우성',
    role: 'DevOps Engineer',
    avatar: '👨‍💻',
    rank: 12,
    contributionRate: 55,
    status: '미흡',
    maxScore: 1.5,
    currentScore: 1.5,
  },
]
